### ISSUE TITLE
Sometimes nullpointerexeption when ending turn

### ISSUE THREAD

**Issue by DanielBerge** [inf112-v19/Blodige-roboter#84]
**Describe the bug**

**To Reproduce**
Got an nullpointer when ending the turn (and the robot died)

**Expected behavior**

**Screenshots**

> 
> ```java
> Exception in thread "LWJGL Application" java.lang.NullPointerException
> 	at no.uib.inf112.core.map.GameMap.getBoardLayerTile(GameMap.java:91)
> 	at no.uib.inf112.core.map.MapInteractOnUser.registerSpecialTiles(MapInteractOnUser.java:45)
> 	at no.uib.inf112.core.map.MapInteractOnUser.scan(MapInteractOnUser.java:31)
> 	at no.uib.inf112.core.RoboRally.round(RoboRally.java:50)
> 	at no.uib.inf112.core.player.PlayerHandler.lambda$null$2(PlayerHandler.java:91)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:259)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:210)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
> ```

**Desktop (please complete the following information):**

**Additional context**

**Comment by DanielBerge** [comment]
Cannot be reproduced
